-- CrateRush
-- constants/events.lua — WoW event name constants. No magic strings in event registration.

local EVT = {}
CrateRush.EVT = EVT

EVT.PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD"
EVT.ZONE_CHANGED_NEW_AREA = "ZONE_CHANGED_NEW_AREA"
EVT.VIGNETTES_UPDATED     = "VIGNETTES_UPDATED"
EVT.GROUP_ROSTER_UPDATE   = "GROUP_ROSTER_UPDATE"
EVT.PLAYER_FLAGS_CHANGED  = "PLAYER_FLAGS_CHANGED"
EVT.NPC_ANNOUNCEMENT      = "CHAT_MSG_MONSTER_SAY"
EVT.NAME_PLATE_UNIT_ADDED = "NAME_PLATE_UNIT_ADDED"

local DOMAIN_EVENT = {}
CrateRush.DOMAIN_EVENT = DOMAIN_EVENT

DOMAIN_EVENT.ZONE_SHARD_STATUS_CHANGED = "zoneShardStatusChanged"
DOMAIN_EVENT.CURRENT_ZONE_SHARD_CHANGED = "currentZoneShardChanged"
DOMAIN_EVENT.ZONE_SHARD_CHANGED         = "zoneShardChanged"
DOMAIN_EVENT.CRATE_STATE_CHANGED        = "crateStateChanged"
DOMAIN_EVENT.CRATE_SIGHTING_SEEN        = "crateSightingSeen"
DOMAIN_EVENT.ACTIVE_TIMER_CHANGED       = "activeTimerChanged"
DOMAIN_EVENT.ACTIVE_TIMER_REMOVED       = "activeTimerRemoved"
DOMAIN_EVENT.TIMER_REMOVAL_REQUESTED    = "timerRemovalRequested"
DOMAIN_EVENT.TIMER_SYNC_RECEIVED        = "timerSyncReceived"
DOMAIN_EVENT.PREDICTION_UPDATED         = "predictionUpdated"
DOMAIN_EVENT.PREDICTION_CLEARED         = "predictionCleared"
DOMAIN_EVENT.PLAYER_CONTEXT_CHANGED     = "playerContextChanged"
DOMAIN_EVENT.CONFIG_CHANGED             = "configChanged"
DOMAIN_EVENT.SYNC_REQUESTED             = "syncRequested"
DOMAIN_EVENT.NOTIFICATION_REQUESTED     = "notificationRequested"
DOMAIN_EVENT.ENEMY_PRESENCE_SCAN_STATE_CHANGED = "enemyPresenceScanStateChanged"
DOMAIN_EVENT.ENEMY_PRESENCE_CHANGED      = "enemyPresenceChanged"
