-- CrateRush
-- constants/protocol.lua - Wire protocol constants for addon-to-addon comms.

local PROTO = {}
CrateRush.PROTO = PROTO

PROTO.VERSION = "1"
PROTO.PREFIX = "CRATERUSH"

PROTO.MSG = {
    TOKEN_REQUEST       = "TOKEN_REQUEST",
    TOKEN_UPDATE        = "TOKEN_UPDATE",
    TIMER_SYNC_REQUEST  = "TIMER_SYNC_REQUEST",
    TIMER_SYNC_RESPONSE = "TIMER_SYNC_RESPONSE",
    TIMER_DELETE        = "TIMER_DELETE",
    CRATE_CYCLE_ANCHOR  = "CRATE_CYCLE_ANCHOR",
    ENEMY_PRESENCE_REPORT = "ENEMY_PRESENCE_REPORT",
}

PROTO.CHANNEL = {
    PARTY   = "PARTY",
    RAID    = "RAID",
    WHISPER = "WHISPER",
}

PROTO.TOKEN_REQUEST_THROTTLE_SECONDS = 10
PROTO.TOKEN_REQUEST_MAX_ATTEMPTS = 3
PROTO.TIMER_SYNC_REQUEST_THROTTLE_SECONDS = 30
