-- CrateRush
-- constants/timing.lua - Timing constants used by addon state checks.

CrateRush.TIMING = CrateRush.TIMING or {}

CrateRush.TIMING.ZONE_SHARD_MISMATCH_GRACE_SECONDS = 5
CrateRush.TIMING.ZONE_CHANGE_SETTLE_SCAN_DELAY_SECONDS = 2.5
CrateRush.TIMING.ZONE_SHARD_POLL_INTERVAL_SECONDS = 1
CrateRush.TIMING.ZONE_SHARD_POLL_DURATION_SECONDS = 15
CrateRush.TIMING.LIFECYCLE_DETECTION_GUARDIAN_SECONDS = 900
CrateRush.TIMING.TIMER_MAX_UNSEEN_CYCLES = 5
CrateRush.TIMING.PLANE_CONFIRM_SECONDS = 3
CrateRush.TIMING.PLANE_ANCHOR_CONFIRM_TICKS = 3
CrateRush.TIMING.PLANE_ANCHOR_CONFIRM_WINDOW_SECONDS = 6
CrateRush.TIMING.PLANE_POSITION_TOLERANCE_DEGREES = 0.05
CrateRush.TIMING.LANDED_GONE_FLYING_CONFIRM_COUNT = 2
CrateRush.TIMING.LANDED_GONE_EXPIRY_SECONDS = 4
CrateRush.TIMING.LANDED_ACTION_SECONDS = 300
CrateRush.TIMING.CLAIMED_LOOT_WINDOW_SECONDS = 58
CrateRush.TIMING.VIGNETTE_SEEN_CACHE_MAX_AGE_SECONDS = 1800
CrateRush.TIMING.VIGNETTE_SEEN_CACHE_MAX_ENTRIES = 1000
CrateRush.TIMING.TRANSITION_GUARD_CACHE_MAX_AGE_SECONDS = 300
CrateRush.TIMING.TRANSITION_GUARD_CACHE_MAX_ENTRIES = 500
CrateRush.TIMING.TIMERBAR_URGENT_SECONDS = 30
CrateRush.TIMING.TIMERBAR_WARNING_SECONDS = 120
