-- CrateRush
-- constants/timing.lua - Timing constants used by addon state checks.

CrateRush.TIMING = CrateRush.TIMING or {}

CrateRush.TIMING.ZONE_SHARD_MISMATCH_GRACE_SECONDS = 5
CrateRush.TIMING.ZONE_CHANGE_SETTLE_SCAN_DELAY_SECONDS = 2.5
CrateRush.TIMING.ZONE_SHARD_POLL_INTERVAL_SECONDS = 1
CrateRush.TIMING.ZONE_SHARD_POLL_DURATION_SECONDS = 15
CrateRush.TIMING.LIFECYCLE_DETECTION_GUARDIAN_SECONDS = 900
CrateRush.TIMING.TIMER_MAX_UNSEEN_CYCLES = 5
CrateRush.TIMING.PLANE_CONFIRM_SECONDS = 3
CrateRush.TIMING.PLANE_CONFIRM_REQUIRED_SIGHTINGS = 3
CrateRush.TIMING.TIMERBAR_URGENT_SECONDS = 30
CrateRush.TIMING.TIMERBAR_WARNING_SECONDS = 120
